apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: colors-fanout-ingress
  namespace: colors-ns
  annotations:
    appgw.ingress.kubernetes.io/backend-path-prefix: /
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: akscolors.penguintrails.com
      http:
        paths:
          - path: /red
            backend:
              serviceName: red-service-cluster-ip
              servicePort: 8080
          - path: /green
            backend:
              serviceName: green-service-cluster-ip
              servicePort: 8080
          - path: /blue
            backend:
              serviceName: blue-service-cluster-ip
              servicePort: 8080
          - path:
            backend:
              serviceName: red-service-cluster-ip
              servicePort: 8080
